- name: Setting up local workstation
  hosts: local
  vars_files:
    - vars/main.yml
  roles:
    - role: packages
      tags:
        - packages

    - role: system
      tags:
        - system

    - role: dotfiles
      tags:
        - dotfiles

    - role: dev
      tags:
        - dev
