- name: Upgrade Packages
  apt:
    upgrade: yes
  become: yes
  become_user: root
  become_method: sudo
  when: debian_upgrade == "yes"

- name: Install Packages
  apt:
    state: present
  become: yes
  become_user: root
  become_method: sudo
  loop: "{{ debian_packages }}"

- name: Configure SystemD Packages
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
    masked: no
    force: no
  become: yes
  become_user: root
  become_method: sudo
  with_items: "{{ debian_services }}"

- name: Install Snap Packages
  snap:
    name: "{{ item }}"
    state: present
  become: yes
  become_user: root
  become_method: sudo
  loop: "{{ snap_packages }}"
