- name: Checking for ssh key
  stat:
    file: ~/.ssh/id_ed25519.pub
  register: sshkey

- name: Pulling Down Git Projects
  git:
    repo: "git@github.com:duclos-cavalcanti/dotfiles.git"
    dest: "~/.dotfiles"
    update: no
  when: sshkey.exists

- name: Stow dotfiles
  ansible.builtin.shell:
    cmd: ./install.sh pc install
    chdir: ~/.dotfiles
